### ISSUE TITLE
Mockups der Ansichten erstellen

### ISSUE THREAD

**Issue by Joniras** [criedl1/DI-3_Mankomania#2]
Wir brauchen von allen Ansichten ein Mockup. Das kann entweder per Hand gezeichnet oder per Tool erstellt werden.

Mögliche Ansichten:
*  Startbildschirm
*  Raum erstellen / beitreten (evtl siehe [hier](https://developers.google.com/games/services/android/turnbasedMultiplayer))
*  etwaige Minispiele
*  Kartenansicht
*  Endansicht 
*  Würfeln

**Comment by Nicolebu1** [comment]
Endbildschirm:

![Endbildschirm](https://user-images.githubusercontent.com/48470246/55424013-90cbe580-557f-11e9-8fe7-edd950e65eec.png)

Raum beitreten:

![Raum_betreten](https://user-images.githubusercontent.com/48470246/55424014-91647c00-557f-11e9-95bf-4156e993abb3.png)

Raum erstellen:

![Raum_erstellen](https://user-images.githubusercontent.com/48470246/55424015-91647c00-557f-11e9-8d83-f7d46a5040ec.png)

Startbildschirm:

![Startbildschirm_alternative_with_placeholder](https://user-images.githubusercontent.com/48470246/55424016-91647c00-557f-11e9-9d54-c659ac172558.png)

Startbildschirm alternative:

![Startbildschirm_with_placeholder](https://user-images.githubusercontent.com/48470246/55424017-91647c00-557f-11e9-83b1-a7e29b2260ef.png)

Würfeln: 

![Würfeln_with_placeholder](https://user-images.githubusercontent.com/48470246/55424351-5c0c5e00-5580-11e9-8c38-46798768c332.png)

Ursprünglich zur Anschauung verwendete Bilder wurden für den Upload durch Platzhalter ersetzt. (Ich war unsicher wegen dem Urheberrecht)
